﻿module.exports.config = {
  name: "chuilientuc",
  version: "3.0.0",
  hasPermssion: 1,
  Rent: 2,
  credits: "Vtuan",
  description: "Spam a content to death (continuous insulting)",
  commandCategory: "War/tag",
  usages: "[User ID]",
  cooldowns: 1
};
const spamThreads = new Map(); 
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
module.exports.run = async function({ api, event, args }) {
  const timedelay = 2;
  const { threadID, messageID } = event;
  if (args[0] === "stop") {
    const state = spamThreads.get(threadID);
    if (state) {
      let stopIndex = state.i; 
      spamThreads.delete(threadID);
      api.sendMessage(`Paused`, threadID, messageID);
    } else {
      api.sendMessage("No one is being insulted!", threadID, messageID);
    }
    return;
  }


  var mention = Object.keys(event.mentions || {})[0];
  if (!mention) return api.sendMessage("You need to tag 1 person you want to insult", event.threadID);
  let name = event.mentions[mention];
  var arraytag = [];
  arraytag.push({ id: mention, tag: name });
  if (!spamThreads.has(threadID)) {
    let i = 0; 
    spamThreads.set(threadID, { i });
    while (spamThreads.has(threadID)) {
      const vtuann = [
        "spicy dog eats shit 🤣🤣",
          "bark it 🤣🤣",
          "dog sucks shit🤣🤣👌",
          "get excited :)) ",
          "slow af 🤣🤣 ",
          "brain balls spicy now🤣🤣 ",
          "worthless speak up quick 🤣🤣 ",
          "brain balls :))) ",
          "you okay? ",
          "stupid af 🤣🤣👌 ",
          "dog eats shit 🐶 ",
          "fake balls :)))) ",
          "so weak😏😏 ",
          "dumb dog👉🤣 ",
          "doing okay =))) ",
          "shaking huh :))) ",
          "fake brain 🤣🤣 ",
          "done yet 🤢🤢 ",
          "can you even get excited  ",
          "kid spicy now =))) ",
          "spicy dick slip 👉🤣",
          "ei ei =)) ",
          "em ei :3 ",
          "running away ",
          "scared huh 🤢🤢 ",
          "look at kid tweaking🤣🤣 👌",
          "too good huh :))) ",
          "why so slow ",
          "eo oyyy:3 ",
          "hoo hoo🤨 ",
          "why so mad 😏😏 ",
          "dog brain getting roasted 🤣🤣🐶 ",
          "hurry up :)) ",
          "get excited :))) ",
          "bark fast =)) ",
          "need help :)) ",
          "keep going :3 ",
          "try harder :))) ",
          "bark louder🤣🤣 ",
          "country whore 🤢🤢 ",
          "country brain dick =)))) ",
          "you good 🤣🤣 ",
          "kkk ",
          "hungry🤣🐶👌 ",
          "eaten yet 🤣🤣 ",
          "not yet :))) ",
          "looking weak :)) ",
          "look fake shit :))) ",
          "eo oyyy:3 ",
          "try it 🤣🤣 ",
          "look at you dumb :))) ",
          "whore 🤣🤣 ",
          "stronger:))) ",
          "type stronger :)) ",
          "look embarrassed z🤣🤘 ",
          "natural please ",
          "tired yet ",
          "dont stop ",
          "bald whore :))) ",
          "fast:)) ",
          "you lagging :)) ",
          "you depressed :))) ",
          "mentally unstable :)) ",
          "need meds :)) ",
          "dying🤣🤣 ",
          "cant breathe :)) ",
          "need oxygen :))) ",
          "are you that sick :))) ",
          "lost mood :))) ",
          "tnh chicken :))) ",
          "why so slow :)) ",
          "brain balls 🤣🤣 ",
          "grandma cunt whore shit🤣🤣 ",
          "fluent please 🤣🤣 ",
          "froze huh :))) ",
          "Im so strong right :))) ",
          ":))) kid crying huh ",
          "youre poor ",
          "scared of me:3 ",
          "huh dick =))) ",
          "feel so sorry:)) ",
          "pity the kid trying🤢🤘 ",
          "but stupid🤣🤣 ",
          ":)) 🤣🤣 ",
          "so spicy :)) ",
          "faded huh ",
          "no inspiration to be excited :))) ",
          "lying cunt :))) ",
          "crying yet :))) ",
          "country whore speak:)) ",
          "signal it :))) ",
          "SOS con fake balls 🤣🤣🤢 ",
          "or or or :))) ",
          "dog eats shit :))) ",
          "fake dog on floor 👌🐶 ",
          "shitting blood yet :))) ",
          "poor no willpower:))",
          "fight back :))) I win ",
          "kkk ",
          "you dead yet :))) ",
          "youre poor em 😏🤣 ",
          "you crave my shit:)) ",
          "your moms a whore youre dumb👉🤣 ",
          "youre salty at me :)) ",
          "rotten brain shit🤢🤢 ",
          "bird face whore🤪🤪 ",
          "holding a grudge 🤨 ",
          "mountain whore :))) ",
          "gay shine =)) ",
          "your mothers whore ",
          "I sentenced your mom :)) ",
          "trash waste😏🤘 ",
          "acting up huh :)) ",
          "whats up ",
          "bark here  ",
          "123 bark😏 ",
          "quick here  ",
          "alo alo hoo hoo  ",
          "beast ",
          "whats wrong  ",
          "scared of mom  ",
          "come on mom wont kill your parents 😏 ",
          "boo :)) ",
          "unstable huh ",
          "whats that  ",
          "you dropped chicken🤪 ",
          "I forbid you to deny ",
          "deny and Ill kill your parents:))) ",
          "get excited quick kaka🤢 ",
          "dumb  ",
          "come on mom says ",
          "dont come Ill extinct you beast ",
          "you like acting up🤨 ",
          "no reply = I win  ",
          "no running ",
          "you quick  ",
          "come here or or  ",
          "dumb hey ",
          "what come here Ill kick you dead ",
          "you crying 👉🤣",
          "bark continuously🤣🤣 ",
          "calling fake friends  ",
          "sucking his balls ",
          "balls black? ",
          "slow labor🤣🤣👌 ",
          "panicking ",
          "unstable 🤮🤮 ",
          "shaking ",
          "running away  ",
          "tired  ",
          "defeated yet 👉😏 ",
          "bark fast🙄🙄👈 ",
          "be brave  ",
          "quick chance to save your mom ",
          "dont tell mom ",
          "fake war :)) ",
          "piling on  ",
          "race here Ill take you all😏👌 ",
          "market thug whats up ",
          "dickhead dogface😢🫵🏻👈🏻 ",
          "no panicking ",
          "gotta win again🙄🙄 ",
          "kkk ",
          "gay powerless cause his mom got cunt destroyed:)))  ",
          "your whore mom powerless cause I roast her only silence:)))  ",
          "acting tough but I roast shaking dick:)))  ",
          "Your mom got dick popped clit:)))  ",
          "gay fake dick wanting to fight and the result:)))  ",
          "your whore mom craves my shit so much:)))  ",
          "got roasted shitless dont dare care:)))  ",
          "strong up why so weak kid:)))  ",
          "your dick shaking yet kid:)))  ",
          "slow how you save your whore mom hurry up:)))  ",
          "damn hes tweaking  ",
          "your whore mom scream?😛  ",
          "you scream kid?😏  ",
          "why salty at me?  ",
          "you bark here😛  ",
          "why your cunt so ugly dog kid?  ",
          "why salty at me😏?  ",
          "why kill your mom=)))  ",
          "you scream kid=)))  ",
          "when okay then act up🤣👈  ",
          "hey gay come scavenge quick😘  ",
          "you fake clearly  ",
          "why you eat my shit😏  ",
          "who let you eat my shit  ",
          "why you so brain dick kid=)))  ",
          "meet me dont shake?😂  ",
          "your whore mom craves my shit so much=)))  ",
          "youre orphan right🤣👈  ",
          "who let you bark did I let you bark?  ",
          "got me poking you worse than a dog=)))  ",
          "try it almost winning😏  ",
          "when can you do me like that?  ",
          "your mom about to die hey  ",
          "damn you chicken barking  ",
          "bark crazy bark hard to be fun😘  ",
          "you stop one second your whore mom stops breathing😏  ",
          "hey dumb dog you scared of me😂  ",
          "you clearly fake why you fake like that?  ",
          "your mom dead yet kid=)))  ",
          "hey gay bark crazy  ",
          "why you bark slow?  ",
          "when can you do me tell me?  ",
          "got me poking you worse than a dog😏  ",
          "bark then Ill forgive?  ",
          "bark crazy for mom?  ",
          "you stop your whore mom dies?  ",
          "salty at me balls popping😏  ",
          "dog brain salty?🤣  ",
          "why you so pathetic=)))  ",
          "your mom got dick tore her cherry🤪  ",
          "your mom got dick mashed into cunt=)))  ",
          "fuck your mom feels so good dick numb=)))  ",
          "huhu look at you like a dick=)))  ",
          "you incest grandma=)))  ",
          "your mom got dick moaning uh uh=)))  ",
          "fuck your mom so refreshing😛  ",
          "I fuck your mom cunt destroyed=)))  ",
          "Hey shine cunt  ",
          "your mom got raped=)))  ",
          "your mom giving cunt to dog lick🤣👈  ",
          "you brain of a cunt  ",
          "beg me Ill forgive😏  ",
          "suck my cunt🤪  ",
          "you barking what?😏  ",
          "heard youre scared of me?  ",
          "nameless no barking?😏 ",
          "what you crave my shit=)))?  ",
          "why you slow kid  ",
          "you have age?😏  ",
          "cunt age eat me😏?  ",
          "I fuck your mom breathless😛 ",
         "dumb kid a bit weak 🤣🤣 ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "kkk ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "bark it 🤣🤣 ",
        "dog sucks shit🤣🤣👌",
        "get excited :)) ",
        "slow af 🤣🤣 ",
        "brain balls spicy now🤣🤣 ",
        "worthless speak up quick 🤣🤣 ",
        "brain balls :))) ",
        "you okay? ",
        "stupid af 🤣🤣👌 ",
        "dog eats shit 🐶 ",
        "fake balls :)))) ",
        "so weak😏😏 ",
        "dumb dog👉🤣 ",
        "doing okay =))) ",
        "shaking huh :))) ",
        "fake brain 🤣🤣 ",
        "done yet 🤢🤢 ",
        "can you even get excited  ",
        "kid spicy now =))) ",
        "spicy dick slip 👉🤣",
        "ei ei =)) ",
        "em ei :3 ",
        "running away ",
        "scared huh 🤢🤢 ",
        "look at kid tweaking🤣🤣 👌",
        "too good huh :))) ",
        "why so slow ",
        "eo oyyy:3 ",
        "hoo hoo🤨 ",
        "why so mad 😏😏 ",
        "dog brain getting roasted 🤣🤣🐶 ",
        "hurry up :)) ",
        "get excited :))) ",
        "bark fast =)) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "need help :)) ",
        "keep going :3 ",
        "try harder :))) ",
        "bark louder🤣🤣 ",
        "country whore 🤢🤢 ",
        "country brain dick =)))) ",
        "you good 🤣🤣 ",
        "kkk ",
        "hungry🤣🐶👌 ",
        "eaten yet 🤣🤣 ",
        "not yet :))) ",
        "looking weak :)) ",
        "look fake shit :))) ",
        "eo oyyy:3 ",
        "try it 🤣🤣 ",
        "look at you dumb :))) ",
        "whore 🤣🤣 ",
        "stronger:))) ",
        "type stronger :)) ",
        "look embarrassed z🤣🤘 ",
        "natural please ",
        "tired yet ",
        "dont stop ",
        "bald whore :))) ",
        "fast:)) ",
        "you lagging :)) ",
        "you depressed :))) ",
        "mentally unstable :)) ",
        "need meds :)) ",
        "dying🤣🤣 ",
        "cant breathe :)) ",
        "need oxygen :))) ",
        "are you that sick :))) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "kkk ",
        "you dead yet :))) ",
        "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "rotten brain shit🤢🤢 ",
        "bird face whore🤪🤪 ",
        "holding a grudge 🤨 ",
        "mountain whore :))) ",
        "gay shine =)) ",
        "your mothers whore ",
        "I sentenced your mom :)) ",
        "trash waste😏🤘 ",
        "acting up huh :)) ",
        "whats up ",
        "bark here  ",
        "123 bark😏 ",
        "quick here  ",
        "alo alo hoo hoo  ",
        "beast ",
        "whats wrong  ",
        "scared of mom  ",
        "come on mom wont kill your parents 😏 ",
        "boo :)) ",
        "unstable huh ",
        "whats that  ",
        "you dropped chicken🤪 ",
        "I forbid you to deny ",
        "deny and Ill kill your parents:))) ",
        "get excited quick kaka🤢 ",
        "dumb  ",
        "come on mom says ",
        "dont come Ill extinct you beast ",
        "you like acting up🤨 ",
        "no reply = I win  ",
        "no running ",
        "you quick  ",
        "come here or or  ",
        "dumb hey ",
        "what come here Ill kick you dead ",
        "you crying 👉🤣 ",
        "bark continuously🤣🤣 ",
        "calling fake friends  ",
        "sucking his balls ",
        "balls black? ",
        "slow labor🤣🤣👌 ",
        "panicking ",
        "unstable 🤮🤮 ",
        "shaking ",
        "running away  ",
        "tired  ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ", 
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "defeated yet 👉😏 ",
        "bark fast🙄🙄👈 ",
        "be brave  ",
        "quick chance to save your mom ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "signal it :))) ",
        "try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "dont tell mom ",
        "fake war :)) ",
        "piling on  ",
        "race here Ill take you all😏👌 ",
        "market thug whats up ",
        "dickhead dogface😢🫵🏻👈🏻 ",
        "you still okay ",
        "mental unstable=) ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "kkk ",
        "look kid crying red eyes😂 ",
        "hphuc insults so deep ",
        "salty salty salty ",
        "dad too good whore😂 ",
        "kid with mom selling pig feed=)) ",
        "your mom makes pig feed with whore ",
        "side job is maid=)) ",
        "kid done crying like crocodile=)) ",
        "kkk ",
        "look at your ugly face ",
        "face full of pimples and scars=)) ",
        "looks disgusting ",
        "milky stinky mouth ",
        "nose not clean yet wanna war ",
        "who let you in the arena whore=) ",
        "huh huh what ",
        "your whore mom led you into arena=)) ",
        "your mom sucked my dick so you could enter arena ",
        "why so mad 😏😏 ",
        "dog brain getting roasted 🤣🤣🐶 ",
        "hurry up :)) ",
        "get excited :))) ",
        "bark fast =)) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "damn the kid with whore mom=)) ",
        "boycott him everyone ",
        "scum not worthy in society😂😂 ",
        "rude cunt fake epileptic=)) ",
        "doing drugs weed then barking nonsense ",
        "why why you silent kid ",
        "you angry yet=)) ",
        "Im the lord you ",
        "you salty at me is natural😂 ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛 ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
          "why you so weak ",
        "try a bit more ",
        "why slow ",
        "excite a bit ",
        "till morning kid ",
        "try a bit kid ",
        "cant do it ",
        "kid try ",
        "why you silent ",
        "chicken what ",
        "tnh chicken ",
        "youre chicken ",
        "huh ",
        "thats right ",
        "arguing huh ",
        "you got anything else ",
        "copycat ",
        "try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "boring ",
        "youre chicken ",
        "log account switching huh ",
        "look at them stupid piling ",
        "everyone hey ",
        "winning again ",
        "winning again ",
        "dick crowd so salty at me🤣🤣 ",
        "come on ",
        "he hung up everyone🤣 ",
        "that weak huh ",
        "whats up ",
        "crying look ",
        "call for help quick ",
        "who can save you:)) ",
        "Im the best ",
        "why you so chicken ",
        "excite quick for me ",
        "dog kid🤣 ",
        "you okay kid ",
        "not okay yet ",
        "beg for mercy kid ",
        "your mom stupid huh ",
        "suck dad dick kid ",
        "fake girl kid:)) ",
        "look at him stupid everyone ",
        "this dog pretending stupid huh ",
        "you okay ",
        "orphan look ",
        "what scared yet ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
          "bark it 🤣🤣 ",
        "dog sucks shit🤣🤣👌 ",
        "get excited :))  ",
        "slow af 🤣🤣 ",
        "brain balls spicy now🤣🤣 ",
        "worthless speak up quick 🤣🤣 ",
        "brain balls :))) ",
        "you okay? ",
        "stupid af 🤣🤣👌 ",
        "dog eats shit 🐶 ",
        "fake balls :)))) ",
        "so weak😏😏 ",
        "dumb dog👉🤣 ",
        "doing okay =))) ",
        "shaking huh :))) ",
        "fake brain 🤣🤣 ",
        "done yet 🤢🤢 ",
        "can you even get excited  ",
        "kid spicy now =))) ",
        "spicy dick slip 👉🤣 ",
        "ei ei =)) ",
        "em ei :3 ",
        "running away ",
        "scared huh 🤢🤢 ",
        "look at kid tweaking🤣🤣 👌 ",
        "need oxygen :))) ",
        "are you that sick:))) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "kkk ",
        "you dead yet :))) ",
        "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "rotten brain shit🤢🤢 ",
        "bird face whore🤪🤪 ",
        "holding a grudge 🤨 ",
        "mountain whore :))) ",
        "gay shine =)) ",
        "your mothers whore ",
        "I sentenced your mom:)) ",
        "trash waste😏🤘 ",
        "acting up huh :)) ",
        "whats up ",
        "bark here  ",
        "123 bark😏 ",
        "quick here  ",
        "alo alo hoo hoo  ",
        "beast ",
        "whats wrong  ",
        "scared of mom  ",
        "come on mom wont kill your parents 😏 ",
        "boo :)) ",
        "unstable huh ",
        "whats that  ",
        "you dropped chicken🤪 ",
        "I forbid you to deny ",
        "deny and Ill kill your parents:))) ",
        "get excited quick kaka🤢 ",
        "dumb  ",
        "come on mom says ",
        "dont come Ill extinct you beast ",
        "you like acting up🤨 ",
        "no reply = I win  ",
        "no running ",
        "you quick  ",
        "come here or or  ",
        "dumb hey ",
        "what come here Ill kick you dead ",
        "you crying 👉🤣 ",
        "bark continuously🤣🤣 ",
        "calling fake friends  ",
        "sucking his balls ",
        "balls black? ",
        "slow labor🤣🤣👌 ",
        "panicking ",
        "unstable 🤮🤮 ",
        "shaking ",
        "running away  ",
        "tired  ",
        "defeated yet 👉😏 ",
        "bark fast🙄🙄👈 ",
        "be brave  ",
        "quick chance to save your mom ",
        "dont tell mom ",
        "fake war :)) ",
        "piling on  ",
        "race here Ill take you all😏👌 ",
          "gay powerless cause his mom got cunt destroyed:)))  ",
        "your whore mom powerless cause I roast her only silence:)))  ",
        "acting tough but I roast shaking dick:))) ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "Your mom got dick popped clit:)))  ",
        "gay fake dick wanting to fight and the result:)))  ",
        "your whore mom craves my shit so much:)))  ",
        "got roasted shitless dont dare care:)))  ",
        "strong up why so weak kid:)))  ",
        "your dick shaking yet kid:)))  ",
        "slow how you save your whore mom hurry up:)))  ",
        "damn hes tweaking  ",
        "your whore mom scream?😛  ",
        "you scream kid?😏  ",
        "why salty at me?  ",
        "you bark here😛  ",
        "why your cunt so ugly dog kid?  ",
        "why salty at me😏?  ",
        "why kill your mom=))) ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "kkk",
        "you dead yet :))) ",
        "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "rotten brain shit🤢🤢 ",
        "bird face whore🤪🤪 ",
        "holding a grudge 🤨 ",
        "mountain whore :))) ",
        "gay shine =)) ",
        "your mothers whore ",
        "I sentenced your mom :)) ",
        "trash waste😏🤘 ",
        "acting up huh :)) ",
        "whats up ",
        "bark here ",
        "123 bark😏 ",
        "quick here ",
        "alo alo hoo hoo ",
        "beast ",
        "whats wrong ",
        "scared of mom ",
        "come on mom wont kill your parents 😏 ",
        "boo :)) ",
        "unstable huh ",
        "whats that ",
        "you dropped chicken🤪 ",
        "I forbid you to deny ",
        "deny and Ill kill your parents:))) ",
        "get excited quick kaka🤢 ",
        "dumb ",
        "come on mom says ",
        "dont come Ill extinct you beast ",
        "you like acting up🤨 ",
        "no reply = I win ",
        "no running ",
        "you quick ",
        "come here or or ",
        "dumb hey ",
        "what come here Ill kick you dead ",
        "you crying 👉🤣 ",
        "bark continuously🤣🤣 ",
        "calling fake friends ",
        "sucking his balls ",
        "balls black? ",
        "slow labor🤣🤣👌 ",
        "panicking ",
        "unstable 🤮🤮 ",
        "shaking ",
        "running away ",
        "tired ",
        "defeated yet 👉😏 ",
        "bark fast🙄🙄👈 ",
        "be brave. ",
        "quick chance to save your mom ",
        "dont tell mom ",
        "fake war :)) ",
        "piling on ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "race here Ill take you all😏👌",
        "market thug whats up ",
        "dickhead dogface😢🫵🏻👈🏻 ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ","try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "try a bit kid ",
        "crying huh ",
        "why crying ",
        "I didnt let you cry ",
        "come quick kid ",
        "whats up ",
        "given up yet ",
        "be strong a bit ",
        "try kid ",
        ":))) ",
        "scared of me huh ",
        "why scared of me ",
        "Im torturing you ",
        "making up stories huh ",
        "salty :)))) ",
        "try kidi ",
        "keep excited ",
        "till morning kid ",
        "not till morning ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "kkk Im the best ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "fight back :))) I win ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "akakaka ",
          "beast ",
        "Ah offering you? ",
        "You have influence dumb dog🫵🤣  ",
        "come on mom wont kill your parents 😏 ",
        "Your dad fucked pig gave birth to you dog  :)) ",
        "unstable huh ",
        "whats that  ",
        "you scared of me chicken🤪 ",
        "I forbid you to deny ",
        "deny and Ill kill your parents:))) ",
        "get excited quick kaka🤢 ",
        "dumb  ",
        "YOU SILENT = YOUR MOM DIES ",
        "dont come Ill extinct you beast ",
        "you like acting up🤨 ",
        "no reply = I win  ",
        "no running ",
        "silence dad wins laborer ",
        "come here or or  ",
        "Look at your face so ugly  ",
        "BRAIN CUNT ORPHAN ",
        "DAD LET YOU BE SILENT YET👉🤣 ",
        "DAD LORD OF SOCIAL MEDIA🤣🤣 ",
        "WHORE MOM DEFECTIVE SPERM  ",
        "sucking his balls ",
          "no reply = I win  ",
        "no running ",
        "silence dad wins laborer ",
        "come here or or  ",
        "Look at your face so ugly  ",
        "BRAIN CUNT ORPHAN ",
        "DAD LET YOU BE SILENT YET👉🤣 ",
        "DAD LORD OF SOCIAL MEDIA🤣🤣 ",
        "WHORE MOM DEFECTIVE SPERM  ",
        "sucking his balls ",
        "balls black? ",
        "slow labor🤣🤣👌 ",
        "IM THE BEST ",
        "unstable 🤮🤮 ",
        "Scared of me to the point of cutting dick  ",
        "running away  ",
        "tired  ",
        "defeated yet 👉😏 ",
        "bark fast🙄🙄👈 ",
        "be brave  ",
        "quick chance to save your mom ",
        "dont tell mom ",
        "fake war :)) ",
        "hjhj  ",
        "try it almost winning😏👌 ",
        "begging win :( ",
        "please😢🫵🏻👈🏻 ",
        "try kkkk almost defeated ",
        "gotta win again🙄🙄 ",
        "slow how you save your whore mom hurry up:)))  ",
        "damn hes tweaking  ",
        "your whore mom scream?😛  ",
        "you scream kid?😏  ",
        "why salty at me?  ",
        "you bark here😛  ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "bark it 🤣🤣 ",
        "dog sucks shit🤣🤣👌",
        "get excited :)) ",
        "slow af 🤣🤣 ",
        "brain balls spicy now🤣🤣 ",
        "worthless speak up quick 🤣🤣 ",
        "brain balls :))) ",
        "you okay? ",
        "stupid af 🤣🤣👌 ",
        "dog eats shit 🐶 ",
        "fake balls :)))) ",
        "so weak😏😏 ",
        "dumb dog👉🤣 ",
        "doing okay =))) ",
        "shaking huh :))) ",
        "fake brain 🤣🤣 ",
        "done yet 🤢🤢 ",
        "can you even get excited  ",
        "kid spicy now =))) ",
        "spicy dick slip 👉🤣",
        "ei ei =)) ",
        "em ei :3 ",
        "running away ",
        "scared huh 🤢🤢 ",
        "look at kid tweaking🤣🤣 👌",
        "too good huh :))) ",
        "why so slow ",
        "eo oyyy:3 ",
        "hoo hoo🤨 ",
        "why so mad 😏😏 ",
        "dog brain getting roasted 🤣🤣🐶 ",
        "hurry up :)) ",
        "get excited :))) ",
        "bark fast =)) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "need help :)) ",
        "keep going :3 ",
        "try harder :))) ",
        "bark louder🤣🤣 ",
        "country whore 🤢🤢 ",
        "country brain dick =)))) ",
        "you good 🤣🤣 ",
        "kkk ",
        "hungry🤣🐶👌 ",
        "eaten yet 🤣🤣 ",
        "not yet :))) ",
        "looking weak :)) ",
        "look fake shit :))) ",
        "eo oyyy:3 ",
        "try it 🤣🤣 ",
        "look at you dumb :))) ",
        "whore 🤣🤣 ",
        "stronger:))) ",
        "type stronger :)) ",
        "look embarrassed z🤣🤘 ",
        "natural please ",
        "tired yet ",
        "dont stop ",
        "bald whore :))) ",
        "fast:)) ",
        "you lagging :)) ",
        "you depressed :))) ",
        "mentally unstable :)) ",
        "need meds :)) ",
        "dying🤣🤣 ",
        "cant breathe :)) ",
        "need oxygen :))) ",
        "are you that sick :))) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "kkk ",
        "you dead yet :))) ",
        "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "youre orphan right🤣👈  ",
        "who let you bark did I let you bark?  ",
        "got me poking you worse than a dog=)))  ",
        "try it almost winning😏  ",
        "when can you do me like that?  ",
        "your mom about to die hey  ",
        "damn you chicken barking  ",
        "bark crazy bark hard to be fun😘  ",
        "you stop one second your whore mom stops breathing😏  ",
        "hey dumb dog you scared of me😂  ",
        "you clearly fake why you fake like that?  ",
        "your mom dead yet kid=)))  ",
        "hey gay bark crazy  ",
        "why you bark slow?  ",
          "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "youre orphan right🤣👈  ",
        "who let you bark did I let you bark?  ",
        "got me poking you worse than a dog=)))  ",
        "try it almost winning😏  ",
        "when can you do me like that?  ",
        "your mom about to die hey  ",
        "damn you chicken barking  ",
        "bark crazy bark hard to be fun😘  ",
        "you stop one second your whore mom stops breathing😏  ",
        "hey dumb dog you scared of me😂  ",
        "you clearly fake why you fake like that?  ",
        "your mom dead yet kid=)))  ",
        "when can you do me tell me?  ",
        "got me poking you worse than a dog😏  ",
        "bark then Ill forgive?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "dog brain salty?🤣  ",
        "why you so pathetic=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "got roasted shitless dont dare care:)))  ",
        "strong up why so weak kid:)))  ",
        "your dick shaking yet kid:)))  ",
        "slow how you save your whore mom hurry up:)))  ",
        "damn hes tweaking  ",
        "your whore mom scream?😛  ",
        "you bark crazy kid?😏  ",
        "why salty at me?  ",
        "bark here hjhj fat kid😛  ",
        "why your cunt so ugly dog kid?  ",
        "why salty at me😏?  ",
        "why kill your mom=)))  ",
        "you scream kid=)))  ",
        "when okay then act up🤣👈  ",
        "hey gay come scavenge quick😘  ",
          "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom got raped=)))  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "kneel beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "why you so brain dick kid=)))  ",
        "meet dad shaking?😂  ",
        "your whore mom craves my shit so much=)))  ",
        "you lost parents right🤣👈  ",
        "who let you bark did I let you bark?  ",
        "got me poking you worse than a dog=)))  ",
        "try it almost winning😏  ",
        "when can you do me like that?  ",
        "your mom got fucked stroke outside motel bring coffin   ",
        "bring 2 for mom and daughter fat kid kkk ",
        "bark crazy bark hard to be fun😘  ",
        "you stop one second your whore mom stops breathing😏  ",
        "hey dumb dog you scared of me😂  ",
        "you clearly fake why you fake like that?  ",
        "your mom dead yet kid=)))  ",
        "hey gay bark crazy  ",
        "why you bark slow?  ",
        "when can you do me tell me?  ",
        "got me poking you worse than a dog😏  ",
        "bark then big bro forgives brain kid?  ",
        "bark crazy for mom?  ",
        "you stop your whore mom dies?  ",
        "salty at me balls popping😏  ",
        "battle with dad open your dog mouth?🤣  ",
        "why you so pathetic need me wipe tears!!!!=)))  ",
        "your mom got dick tore her cherry🤪  ",
        "your mom got dick mashed into cunt=)))  ",
        "fuck your mom feels so good dick numb=)))  ",
        "huhu look at you like a dick=)))  ",
        "you incest grandma=)))  ",
        "your mom got dick moaning uh uh=)))  ",
        "fuck your mom so refreshing😛  ",
        "I fuck your mom cunt destroyed=)))  ",
        "Hey shine cunt  ",
        "your mom giving cunt to dog lick🤣👈  ",
        "you brain of a cunt  ",
        "kneel beg me Ill forgive😏  ",
        "suck my cunt🤪  ",
        "you barking what?😏  ",
        "heard youre scared of me?  ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "hey gay shine 🤣🤣 ",
        "let dad open your mouth 😛😛 🤣🤣 ",
        "suck dads shit say its good right🤣🤣👌",
        "fast :)) ",
        "lagging brain balls 🤣🤣 ",
        "brain balls spicy now🤣🤣 ",
        "worthless speak up quick 🤣🤣 ",
        "Your mom got fucked cunt torn🤣 :))) ",
        "Your mom got fucked bridge collapsed sewer . ",
        "Your dad cut dick eat🤣🤣👌 ",
        "Chicken whore🐔  wanna eat us 🍔🐶 ",
        "Beast no skill wanna fight me fake:)))) ",
        "so weak😏😏 ",
        "Born from fake sperm👉🤣 ",
        "doing okay =))) ",
        "Dad is lord saint🐒🎶 here to shut up heroes tk heroes:))) ",
        "You using prehistoric language kakaa 🤣🤣 ",
        "You ran out of language whore stupid prehistoric cmnr🤢🤢 ",
        "can you even get excited  ",
        "kid spicy now =))) ",
        "spicy dick slip 👉🤣",
        "Ooh Ooh kid salty at dad cut dick 🤣 =)) ",
        "Your mom cut throat die:3 ",
        "SILENCE IS YOUR WHOLE FAMILY DEAD UNDER 💀TAY CHA😣∋⓪①②③( =ノωヽ=)◉‿◉🐮🐮 ",
        "Dad win cmnr❦❦❦❦🤢🤢 ",
        "poor orphan 😮‍💨😮‍💨🤣🤣 👌",
        "too good huh :))) ",
        "why so slow ",
        "gay fake dick wanting to fight and the result:))):3 ",
        "battle with dad must split dog brain answer hear🤨 ",
        "why so mad 😏😏 ",
        "dog brain getting roasted 🤣🤣🐶 ",
        "Fake crowd frustrated at dad clearly😗❗",
        "How you doing okay popping out 🤔",
        "Your dad is lord mxh stupid🤣",
        "Salty at dad so much right",
        "Pissing blood look stupid🤣",
        "Honey lying cunt making up stories😗",
        "Your level what age to eat me🤣",
        "Honey excited abnormally🤣",
        "Salty at me inside cant do anything🤔🌶", 
        "Salty red butterfly stupid🌶❗",
        "Dick salty at me red balls🌶❗🤪",
        "When have skill beast",
        "Your face like mutant from womb🤪",
        "Hey morally decayed🤪",
        "Rotten personality bottom of hybrid 🤣",
        "The one with no status equal to a beast anymore🤪🤣",
        "Dad types you a whole ocean🤣",
        "Type you scared mind blown🤪",
        "Type you transcend to other world🤣",
        "Whore being tortured by dad🤪",
        "Monkey face dick❗",
        "Beast human face",
        "Monkey human face🐵❗",
        "Hybrid salty at me🌶❗",
        "Crying yet kid🤣❗",
        "Unstable yet🤣",
        "Crying mommy🤣",
        "How you doing sis🤣",
        "You got dad making you salty🌶🤣",
        "Go tell mom yet🤣",
        "Why not excited anymore🤣",
        "Type so weak🤣",
        "Type tweak cunt blood up",
        "Get excited dad watch🤣",
        "Salty gone crazy yet🤣",
        "Just typed a bit already tired🤣",
        "Got me give you bunch of onions in mouth🤣🤣",
        "Type tweak tweak lively come on🤣",
        "Unstable cmnr🤣",
        "Brain got dad disabled yet🤣",
        "Hey beast chewing words🤣",
        "Exhausted out of energy yet🤣",
        "Hey salty piss no blood drop yet🤣",
        "Your dad specializes in treating fakes🤣",
        "Honey whats up🤣",
        "Not excited like start anymore🤣",
        "Eo oi:>🤪",
        "Still alive😗",
        "You being tortured by dad:3",
        "Dad forbids you making up stories🤔",
        "Dad quin beast hey🤪",
        "Eager to get quin by dad so much🤪",
        "Hey monster🤪",
        "Youre monster in jungle🤪",
        "You think youre playing beauty and beast🤪",
        "You think youre playing beauty and beast🤪",
        "Get out of that fantasy kid🤪",
        "Why got roasted by dad degenerated🤪",
        "Living so poor beast fake hey😳",
        "Crying dad mom🤪",
        "Salty mom🌶❗",
        "Lgbt deploying formation against dad🤪❗",
        "Stupid piling on still wanna pile❗🦋",
        "Look at disabled holding hotkey excited🤣",
        "Your dad lord rules fakes🤪",
        "Your dad feeds shit into your mouth😏",
        "Hey stupid whore🤣",
        "How you doing okay",
        "Or okay popping out😴😳",
        "Look at your face obviously not okay😳",
        "Monkey tortured by dad😁",
        "Got dad exiled to hell😗",
        "To reincarnate as beast🤣",
        "Dont be salty at dad and do reckless❗❗",
        "Look at your face enough to know how salty🌶",
        "You pissing blood🌶🤣",
        "Quick hands up🤣",
        "Quick scoop cunt blood for dad drink🤣",
        "Done already beast got insulted by me🤣",
        "Insulted like low level animal🤣",
        " stupid 4 limbs developed🤪",
        "Suddenly excited sideways🤣",
        "Excited sideways makes me so scared 😱",
        "Excited a bit then died🤪",
        "Pissing blood sizzling🤣❗",
        "Repenting yet ❗🤣",
        "So salty drink dog piss to cool down🤣",
        "Crying die your mother whore",
        "Reincarnate your mom hybrid🤣",
        "Stupid dumb ignorant🤣",
        "Got dad degenerated into dumb dog🤣",
        "Why you dumb like 🐮 v",
        "Salty salty salty at dad🤣",
        "Who let you be salty at dad🤣",
        "Salty leave some for others🤣",
        "Salty all the worlds share whats that 🤨",
        "Hey wild beast🤣",
        "Congenital deformity brain dead",
        "Dying mom yet🤨",
        "Your dad lord mxh who can do me😁",
        "You crying yet🤣",
        "Test tube fetus also knows crying🤣",
        "You bark like your dog bark it🤣", 
        "Hey why salty at dad😳",
        "Who let you be salty at dad😗",
        "Monkey disguised as people harming innocents🤣",
        "Ran out of words beast stupid hey",
        "Why repeat continuously🤣",
        "Type long no damage why type🤣",
        "Youre long march whore🤣",
        "Beast prostituting selling like selling virgin miss🤣",
        "Hey whore talking nonsense🤣",
        "Dont slap yourself in face anymore🤣",
        "Look at you obviously not okay!",
        "You know I specialize in treating your kind",
        "Why you so fake🤣", 
        "When stop being fake beast stupid",
        "After this probably stop being fake huh",
        "Hey congenital stupid beast",
        "Youre beast born already stupid🤣",
        "Hey ghost street corner🤪",
        "You get excited strong🤪",
        "Why suddenly weak like limp dick🤣",
        "Your mom got incest fucked cunt shaking🤣",
        "Dick not hairy yet wanna fuck this fuck that🤣",
        "stupid dog showing off skill get kicked🤣", 
        "dumb trying to act okay", 
        "or or or why you excited ", 
        "war people 2024 excited look everyone", 
        "got me poking your dick numb ", 
        "look at brain balls fake acting with bot so dumb 🤣", 
        "or dumb who hung you kid ", 
        "suddenly hung chicken ran out of words", 
        "who pretends scared so kid less embarrassed😝", 
        "dumb eats my shit acting tough", 
        "why you so fake wake up",
          "dumb kid a bit weak 🤣🤣 ",
        "nameless no barking?😏  ",
        "what you crave my shit=)))?  ",
        "why you slow kid  ",
        "you have age?😏  ",
        "cunt age eat me😏?  ",
        "I fuck your mom breathless😛 ",
        "no panicking ",
        "gotta win again🙄🙄 ",
        "kkk ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "bark it 🤣🤣 ",
        "dog sucks shit🤣🤣👌",
        "get excited :)) ",
        "slow af 🤣🤣 ",
        "brain balls spicy now🤣🤣 ",
        "worthless speak up quick 🤣🤣 ",
        "brain balls :))) ",
        "you okay? ",
        "stupid af 🤣🤣👌 ",
        "dog eats shit 🐶 ",
        "fake balls :)))) ",
        "so weak😏😏 ",
        "dumb dog👉🤣 ",
        "doing okay =))) ",
        "shaking huh :))) ",
        "fake brain 🤣🤣 ",
        "done yet 🤢🤢 ",
        "can you even get excited  ",
        "kid spicy now =))) ",
        "spicy dick slip 👉🤣",
        "ei ei =)) ",
        "em ei :3 ",
        "running away ",
        "scared huh 🤢🤢 ",
        "look at kid tweaking🤣🤣 👌",
        "too good huh :))) ",
        "why so slow ",
        "eo oyyy:3 ",
        "hoo hoo🤨 ",
        "why so mad 😏😏 ",
        "dog brain getting roasted 🤣🤣🐶 ",
        "hurry up :)) ",
        "get excited :))) ",
        "bark fast =)) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "need help :)) ",
        "keep going :3 ",
        "try harder :))) ",
        "bark louder🤣🤣 ",
        "country whore 🤢🤢 ",
        "country brain dick =)))) ",
        "you good 🤣🤣 ",
        "kkk ",
        "hungry🤣🐶👌 ",
        "eaten yet 🤣🤣 ",
        "not yet :))) ",
        "looking weak :)) ",
        "look fake shit :))) ",
        "eo oyyy:3 ",
        "try it 🤣🤣 ",
        "look at you dumb :))) ",
        "whore 🤣🤣 ",
        "stronger:))) ",
        "type stronger :)) ",
        "look embarrassed z🤣🤘 ",
        "natural please ",
        "tired yet ",
        "dont stop ",
        "bald whore :))) ",
        "fast:)) ",
        "you lagging :)) ",
        "you depressed :))) ",
        "mentally unstable :)) ",
        "need meds :)) ",
        "dying🤣🤣 ",
        "cant breathe :)) ",
        "need oxygen :))) ",
        "are you that sick :))) ",
        "lost mood :))) ",
        "tnh chicken :))) ",
        "why so slow :)) ",
        "brain balls 🤣🤣 ",
        "grandma cunt whore shit🤣🤣 ",
        "fluent please 🤣🤣 ",
        "froze huh :))) ",
        "Im so strong right :))) ",
        ":))) kid crying huh ",
        "youre poor ",
        "scared of me:3 ",
        "huh dick =))) ",
        "feel so sorry:)) ",
        "pity the kid trying🤢🤘 ",
        "but stupid🤣🤣 ",
        ":)) 🤣🤣 ",
        "so spicy :)) ",
        "faded huh ",
        "no inspiration to be excited :))) ",
        "lying cunt :))) ",
        "crying yet :))) ",
        "country whore speak:)) ",
        "signal it :))) ",
        "SOS con fake balls 🤣🤣🤢 ",
        "or or or :))) ",
        "dog eats shit :))) ",
        "fake dog on floor 👌🐶 ",
        "shitting blood yet :))) ",
        "poor no willpower:)) ",
        "fight back :))) I win ",
        "kkk ",
        "you dead yet :))) ",
        "youre poor em 😏🤣 ",
        "you crave my shit:)) ",
        "your moms a whore youre dumb👉🤣 ",
        "youre salty at me :)) ",
        "rotten brain shit🤢🤢 ",
        "Fake crowd frustrated at dad clearly😗❗",
        "How you doing okay popping out 🤔 ",
        "Your dad is lord mxh stupid🤣 ",
        "Salty at dad so much right ",
        "Pissing blood look stupid🤣 ",
        "Honey lying cunt making up stories😗 ",
        "Your level what age to eat me🤣 ",
        "Honey excited abnormally🤣 ",
        "Salty at me inside cant do anything🤔🌶❗ ", 
        "Salty red butterfly stupid🌶❗ ",
        "Dick salty at me red balls🌶❗🤪 ",
          "your mom got fucked cunt torn ??😜😈👈💪 ",
        "you silent dumb😆 {name)",
        "your mom mouth catching my cum 😍😍 ",
        "you brain balls whore dog beast😜 ",
        "you wild beast dumb😜 ",
        "I slice your mom cunt grill ",
        "dad cut your dad balls for mom eat🙂😎 ",
        "dumb lick dad ass🥸 ",
        "you like a beast😆 ",
        "you have brain ???💀 ",
        "you lose to me dog brain🤖 ",
        "youre scavenger you dont know😼 ",
        "dad always win👅 ",
        "disabled scavenger dad🖐 ",
        "brain balls kid ",
        "your dad is mxh lord brain 😇 ",
        "you have brain dumb dog ",
        "youre dads laborer🤡 ",
        "your parents got balls cut😹 ",
        "your mom got cunt dug splattering ",
        "your mom got AIDS kids pump impotent👽 ",
        "your dad got tortured like a dog 👹👹 ",
        "I let your mom suck my dick 😽 ",
        "save your mom unfilial kid 😹 ",
        "you stupid or what ?😵‍💫 ",
        "you fake acting laborer🎃 ",
        "your words make dad salty 👻👻 ", 
        "whore your mom disabled👽 ",
        "youre alien 💩🤮 ",
        "your parents need you to save them 😪 ",
        "your mom still waiting for me to put dick in cunt 🤣 ",
        "your dad got given dick hard drug 🤩🤩 ",
        "your parents got balls shoved in🤪 ",
        "your parents cant do anything to me 🤭 ",
        "your dad blind now dumb 😱 ",
        "your mom got tits sliced you dont know🤔🤔 ",
        "your mom got head chopped off🙄👌👈 ",
        "your mom still naked kneels before me 🦶🫵 ",
        "save your mom 🦾 ",
        "you stupid disabled👅 ",
        "you like wild beast 👩‍🦰 ",
        "kid not born yet played with dad👧 ",
        "bottom of society💩💩 ",
        "your mom catches my shit eats deliciously😈 ",
        "your dad got hemorrhoids pulled out 🙀 ",
        "youre unfilial 👾 ",
        "youre wild beast why silent😹 ",
        "bark it cha nghe 🙀 ",
        "dad waiting for you 👹 ",
        "youre dumb whore 🤕 ",
        "dad undefeated all war arenas ?? 👹👹 ",
        "mom then Im the lord 😮‍💨 ",
        "Im torturing beasts like you😼 ",
        "youre not even my dog ☠️ ",
        "you got dick shoved in face🥴 ",
        "I fuck your girl cunt blown ",
          "🤣🤣🤣",
        "I make 3 of them smash together ",
        "Suck Dick quick here kid ",
        "You hold grudge to next life🤨 ",
        "bark quick dumb salty at me🌶 ",
        "Excite quick disabled orphan 🤣🤣🤣 ",
        "Or borrow mom phone type ",
        "dad fuck your mom dead ",
        "dog brain orphan salty at dad 🤣🤣 ",
        "dog brain dick excite quick  ",
        "You sip your moms cunt blood say fatty ",
        "Laborer come dad tell something ",
        "Cant do anything to me salty dog brain ",
        "Find some damaging words ",
        "make dad salty 🫣🫣🫣 ",
        "You that poor shit brain ",
        "dog salty at dad 🫣🫣🫣 ",
        "You take rat corpse stuff in moms cunt ",
        "scared of dad lying cunt kid 👉🤣🤣🤣 ",
        "Brain sterile stupid kneel to dad Find some damaging words ",
        "Brain sterile stupid kneel to dad kkk ",
        "unstable dumb hey ",
        "words no damage 🫣🫣 ",
        "why weak gay silent Ill cut your dads head ",
        "poor quality dog ",
        "just fuck and sing like Quang Tho, fuck done then take wrench ring bell boong boong, take wrench ring bell coong coong. ☺ ",
        "brain balls gay salty🤣🤣 ",
          "fake balls salty ",
          "balls burst yet kid "
      ];
      const content = vtuann[i % vtuann.length];
      await api.sendMessage({
        body: `${content}` + name, mentions: arraytag },threadID)
      await delay(timedelay * 1000);
      if (spamThreads.has(threadID)) {
        i++;
        spamThreads.get(threadID).i = i; 
      }
    }
  } else {
    api.sendMessage(`Hello there <3!`, threadID, messageID);
  }
};
